version: '3.9'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=h2
    ports:
      - "3000:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    command: ["start-dev"]  # Usado para versões recentes do Keycloak 17+

volumes:
  keycloak_data: 
