spring:
  jpa:
    database: MYSQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cuidapet_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&useTimezone=true
    username: root
    password: 123456
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:3000/realms/dev
          jwk-set-uri: http://localhost:3000/realms/dev/protocol/openid-connect/certs
keycloak:
  url-login: http://localhost:3000/realms/dev/protocol/openid-connect/token
  client-id: app_cuidapet
  auth-server-url: http://localhost:3000
  client-secret: 4nUW5YFRFxhJmcqClgL6WJsUJ0lg6gYR
  grant-type: password
  realm: dev
jwtSecret: yfiAQyDNAcj4tTf2fsYSzfUP729i7oKxsRn3s0Ruk40IJGBi80
  