spring:
  jpa:
    database: MYSQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cuidapet_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&useTimezone=true
    username: root
    password: 123456
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://hksntech.com.br:8443/realms/cuidapet
          jwk-set-uri: https://hksntech.com.br:8443/realms/cuidapet/protocol/openid-connect/certs
keycloak:
  url-login: https://hksntech.com.br:8443/realms/cuidapet/protocol/openid-connect/token
  client-id: app_cuidapet
  auth-server-url: https://hksntech.com.br:8443
  client-id-admin: admin_cuidapet
  client-admin-secret: SHN6BDnUGXBeMP6kz0cO1wB8fTPDwbLc
  grant-type: password
  realm: cuidapet
jwtSecret: yfiAQyDNAcj4tTf2fsYSzfUP729i7oKxsRn3s0Ruk40IJGBi80
  